### ISSUE TITLE
Finite Element Meshes

### ISSUE THREAD

**Issue by KristofferC** [JuliaIO/MeshIO.jl#19]
What is the reaction to using this package for loading meshes typically used by Finite Element programs (Abaqus .inp meshes, GMSH .gmsh, etc).

I believe it will be hard to fit these different meshes into a nice concrete type that isn't more than wrapping a Dict but being able to have one place where you can get your FEM mesh from file -> julia dict is useful. I see many people implementing their own mesh readers over and over in different packages. Waste of time.

**Comment by SimonDanisch** [comment]
Yeah, I got quite sad by this as well... One million mesh types and loaders/writers deeply hidden in some package... That's exactly what I was trying to avoid when developing MeshIO and FileIO ;)
I'm very open to any Types/ideas/libraries to improve on this!
