### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by rdeits** [JuliaIO/MeshIO.jl#33]
Could you please tag a v0.1.0 release so that we can have Julia v0.6 support, provided you're happy with the state of the package? 

(I don't have bits for this repo, so I can't do it myself)

**Comment by rdeits** [comment]
ping @SimonDanisch 😉

**Comment by SimonDanisch** [comment]
Woops...
https://github.com/JuliaLang/METADATA.jl/pull/9922

**Comment by rdeits** [comment]
Thank you!
