### ISSUE TITLE
Load OBJ and 2DM parsing does not consider pointtype/normaltype/uvtype

### ISSUE THREAD

**Issue by GerhardHippmann** [JuliaIO/MeshIO.jl#77]
For 2DM and OBJ `load` uses Float32 for parsing, regardless of pointtype/normaltype/uvtype. As a consequence data is rounded accordingly. For MSH Float64 is used.

For OFF, PLY and STL element types are considered as expected.

**Comment by karelispanagiotis** [comment]
When I use `mesh = load("fname.obj"; pointtype=Point3 ` I get an error

> ERROR: MethodError: no method matching parse(::Type{Any}, ::SubString{String})

**Comment by sjkelly** [comment]
Fixed in https://github.com/JuliaIO/MeshIO.jl/pull/78
